# Generated by Django 4.1.4 on 2022-12-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
