# Generated by Django 4.1.4 on 2022-12-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
