# Generated by Django 4.1.4 on 2022-12-20 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_remove_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_quantity',
        ),
    ]
